# Generated by Django 5.1.2 on 2024-10-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('true_answers', models.IntegerField()),
                ('false_answers', models.IntegerField()),
                ('clear_answers', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('usingCigar', models.BooleanField()),
                ('usingAlcohol', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('birth_date', models.DateTimeField()),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('result_list', models.ManyToManyField(related_name='exams', to='api.resultmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportModelTYT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_list', models.ManyToManyField(related_name='daily_reports_tyt', to='api.resultmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportModelAYT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_list', models.ManyToManyField(related_name='daily_reports_ayt', to='api.resultmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('field', models.CharField(max_length=255)),
                ('daily_report_list_ayt', models.ManyToManyField(blank=True, related_name='users', to='api.dailyreportmodelayt')),
                ('daily_report_list_tyt', models.ManyToManyField(blank=True, related_name='users', to='api.dailyreportmodeltyt')),
            ],
        ),
    ]
